up

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,73 +1,181 @@
 #!/bin/bash
-clear
-#â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
-# CRIADOR POR @VPS_MANAGER
-# VERSAO 1.0
-# SLOW DNS TUNNEL
-#â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
 
-RED='\033[1;31m'
+cor1='\033[41;1;37m'
+cor2='\033[44;1;37m'
+scor='\033[0m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
-CORTITLE='\033[1;41m'
 SCOLOR='\033[0m'
-banner='
- ___ _    _____      _____  _  _ ___ 
-/ __| |  / _ \ \    / /   \| \| / __|
-\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
-|___/____\___/ \_/\_/ |___/|_|\_|___/'
 
-echo -e "${CORTITLE}=====================================${SCOLOR}" 
-echo -e "${CORTITLE}       CLIENTE SLOWDNS       ${SCOLOR}"
-echo -e "${CORTITLE}=====================================${SCOLOR}" 
-echo -e "${RED}$banner${SCOLOR}"
-[[ ! -e dns ]] && {
-    yes| termux-setup-storage > /dev/null 2>&1
-    unset LD_PRELOAD > /dev/null 2>&1
-    cd $HOME
-    mv slowdns $PREFIX/bin/slowdns
-    chmod +x $PREFIX/bin/slowdns
-    [[ $(grep -c 'slowdns' $PREFIX/etc/profile) == '0' ]] && echo 'slowdns' >> $PREFIX/etc/profile
-    echo -e "\n${GREEN}BAIXANDO O SCRIPT POR FAVOR AGUARDE ! ${SCOLOR}"
-    curl -O https://github.com/fabricio94b/VPS-MANAGER-1.0/raw/main/Modulos/dns > /dev/null 2>&1
-    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SCRIPT BAIXADO ! DA PROXIMA VEZ\nEXECULTE APENAS O COMANDO ${RED}(${GREEN}slowdns${RED})\n${YELLOW}MESMO QUE VOCÃŠ ESTEJA OFFLINE !${SCOLOR}"
-    chmod +x dns
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@VPS_MANAGER" ]] && {
+	ram1=$(free -h | grep -i mem | awk {'print $2'})
+	ram2=$(free -h | grep -i mem | awk {'print $4'})
+	ram3=$(free -h | grep -i mem | awk {'print $3'})
+	uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
+	system=$(cat /etc/issue.net)
+	fun_bar() {
+		comando[0]="$1"
+		comando[1]="$2"
+		(
+			[[ -e $HOME/fim ]] && rm $HOME/fim
+			[[ ! -d /etc/VPSManager ]] && rm -rf /bin/menu
+			${comando[0]} >/dev/null 2>&1
+			${comando[1]} >/dev/null 2>&1
+			touch $HOME/fim
+		) >/dev/null 2>&1 &
+		tput civis
+		echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
+		while true; do
+			for ((i = 0; i < 18; i++)); do
+				echo -ne "\033[1;31m#"
+				sleep 0.1s
+			done
+			[[ -e $HOME/fim ]] && rm $HOME/fim && break
+			echo -e "\033[1;33m]"
+			sleep 1s
+			tput cuu1
+			tput dl1
+			echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
+		done
+		echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+		tput cnorm
+	}
+
+	verif_ptrs() {
+		porta=$1
+		PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
+		for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
+			svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
+			[[ "$porta" = "$pton" ]] && {
+				echo -e "\n\033[1;31mPORTA \033[1;33m$porta \033[1;31mEM USO PELO \033[1;37m$svcs\033[0m"
+				sleep 3
+				fun_conexao
+			}
+		done
+	}
+
+
+	x="ok"
+	fun_conexao() {
+		while true $x != "ok"; do
+			[[ ! -e '/home/vpsmanager' ]] && exit 0
+			clear
+			echo -e "\E[44;1;37m                MODO DE CONEXAO                 \E[0m\n"
+			echo -e "\033[1;32mSERVICO: \033[1;33mOPENSSH \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
+			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+				sts9="\033[1;32m◉ "
+			} || {
+				sts9="\033[1;31m○ "
+			}
+			
+           [[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mCHISEL: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts8="\033[1;32m◉ "
+			} || {
+				sts8="\033[1;31m○ "
+			}
+			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts7="\033[1;32m◉ "
+			} || {
+				sts7="\033[1;31m○ "
+			}
+
+			[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mOPENVPN: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts5="\033[1;32m◉ "
+			} || {
+				sts5="\033[1;31m○ "
+			}
+
+			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mPROXY SOCKS \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts4="\033[1;32m◉ "
+			} || {
+				sts4="\033[1;31m○ "
+			}
+			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mSSL TUNNEL \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts3="\033[1;32m◉ "
+			} || {
+				sts3="\033[1;31m○ "
+			}
+			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mDROPBEAR \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
+				sts2="\033[1;32m◉ "
+			} || {
+				sts2="\033[1;31m○ "
+			}
+			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mSQUID \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
+				sts1="\033[1;32m◉ "
+			} || {
+				sts1="\033[1;31m○ "
+			}
+			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+			echo ""
+			echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mOPENSSH $sts6\033[1;31m
+[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mSQUID PROXY $sts1\033[1;31m
+[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mDROPBEAR $sts2\033[1;31m
+[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mOPENVPN $sts5\033[1;31m
+[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mPROXY SOCKS $sts4\033[1;31m
+[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
+[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts9\033[1;31m
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+			echo ""
+			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+			echo ""
+			tput civis
+			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
+			read x
+			tput cnorm
+			clear
+			case $x in
+			1 | 01)
+				fun_openssh
+				;;
+			2 | 02)
+				fun_squid
+				;;
+			3 | 03)
+				fun_drop
+				;;
+			4 | 04)
+				fun_openvpn
+				;;
+			5 | 05)
+				fun_socks
+				;;
+			6 | 06)
+				inst_ssl
+				;;
+			7 | 07)
+				fun_sslh
+				;;
+			8 | 08)
+				fun_chisel
+                ;; 	
+		    9 | 09)
+				slow_dns
+				;;
+			10 | 10)
+				menu
+				;;
+			0 | 00)
+				echo -e "\033[1;31mSaindo...\033[0m"
+				sleep 2
+				clear
+				exit
+				;;
+			*)
+				echo -e "\033[1;31mOpcao invalida !\033[0m"
+				sleep 2
+				;;
+			esac
+		done
+	}
+	fun_conexao
 }
-[[ ! -e $HOME/credenciais ]] && {
-    ns=$1
-    [[ -z "$ns" ]] && {
-        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
-        exit 0
-    }
-    chave=$2
-    [[ -z "$chave" ]] && {
-        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
-        exit 0
-    }
-    echo -e "$ns\n$chave" > $HOME/credenciais
-} || {
-    perg=$(echo "${SCOLOR}[s/n]: ")
-    echo -e "\n${YELLOW}O SCRIPT JA ESTÃ CONFIGURADO COM UM\nSEEVIDOR E ESTA PRONTO PARA CONEXAO"
-    read -p "$(echo -e "${GREEN}QUER CONTINUAR COM O MESMO?${SCOLOR} [s/n]: ")" -e -i s opc
-    [[ "$opc" != @(s|sim|S|SIM) ]] && {
-        rm $HOME/credenciais dns > /dev/null 2>&1
-        rm $PREFIX/bin/slowdns > /dev/null 2>&1
-        sed -i '/slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
-        echo -e "\n${RED}SCRIPT REMOVIDO !${SCOLOR}"
-        rm slowdns > /dev/null 2>&1
-        exit 0
-    } || {
-        unset LD_PRELOAD > /dev/null 2>&1
-        ns=$(sed -n 1p $HOME/credenciais)
-        chave=$(sed -n 2p $HOME/credenciais)
-    }
-}
-dns=$3
-[[ -z "$dns" ]] && {
-    dns='187.50.250.115'
-}
-echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}PARA CONTINUAR CERTIFIQUE-SE DE\nESTÃ APENAS COM OS ${RED}(${YELLOW}DADOS MOVEIS${RED})\n${YELLOW}ATIVADO ${GREEN}ENTER ${YELLOW}PARA CONTINUAR.. ${SCOLOR}"; read
-$HOME/dns -udp ${dns}:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &
-echo -e "\n${RED}[${GREEN}âˆš${RED}]${SCOLOR} - ${GREEN}SLOWDNS INICIADO!${SCOLOR} - ${RED}[${GREEN}âˆš${RED}]\n\n${RED}[${YELLOW}!${RED}] ${YELLOW}AGORA CONECTE-SE EM UM APP VPN\nOU CLICK EM ${GREEN}ENTER ${RED}PARA DESCONECTAR ${SCOLOR}"; read
-piddns=$(ps x| grep -w 'dns' | grep -v 'grep'| awk -F' ' {'print $1'})
-[[ ${piddns} != '' ]] && kill ${piddns} > /dev/null 2>&1
